/* 
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
#![allow(unused_imports)]

use serde_json::Value;
use bigdecimal::BigDecimal;
use chrono::{Date, NaiveDateTime, NaiveDate, DateTime, FixedOffset, Utc};

use crate::models::*;
use crate::date_serializer;
use crate::date_serializer_opt;
use crate::serialize_quoted_numbers;
use crate::serialize_quoted_numbers_opt;
//Uncomment this to deal with limited rfc support on server side
//use crate::datetime_serializer::*;

#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct AppTypesResponseEntry {
  #[serde(rename = "appTypes")]
  #[serde(default)]
  app_types: Option<Vec<String>> 
}

impl AppTypesResponseEntry {
  pub fn new() -> AppTypesResponseEntry {
    AppTypesResponseEntry {
      app_types: None
    }
  }

  pub fn set_app_types(&mut self, app_types: Vec<String>) {
    self.app_types = Some(app_types);
  }

  pub fn with_app_types(mut self, app_types: Vec<String>) -> AppTypesResponseEntry {
    self.app_types = Some(app_types);
    self
  }

  pub fn app_types(&self) -> Option<&Vec<String>> {
    self.app_types.as_ref()
  }

  pub fn reset_app_types(&mut self) {
    self.app_types = None;
  }


  pub fn validate(&self) {
  }

}


