/* 
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
#![allow(unused_imports)]

use serde_json::Value;
use bigdecimal::BigDecimal;
use chrono::{Date, NaiveDateTime, NaiveDate, DateTime, FixedOffset, Utc};

use crate::models::*;
use crate::date_serializer;
use crate::date_serializer_opt;
use crate::serialize_quoted_numbers;
use crate::serialize_quoted_numbers_opt;
//Uncomment this to deal with limited rfc support on server side
//use crate::datetime_serializer::*;

#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct AppResponseEntry {
  #[serde(rename = "app")]
  #[serde(default)]
  app: Option<App> 
}

impl AppResponseEntry {
  pub fn new() -> AppResponseEntry {
    AppResponseEntry {
      app: None
    }
  }

  pub fn set_app(&mut self, app: App) {
    self.app = Some(app);
  }

  pub fn with_app(mut self, app: App) -> AppResponseEntry {
    self.app = Some(app);
    self
  }

  pub fn app(&self) -> Option<&App> {
    self.app.as_ref()
  }

  pub fn reset_app(&mut self) {
    self.app = None;
  }


  pub fn validate(&self) {
  }

}


