/* 
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BasicAuthMethodDto {
  #[serde(rename = "authType")]
  auth_type: Option<String>,
  #[serde(rename = "uuid")]
  uuid: Option<String>
}

impl BasicAuthMethodDto {
  pub fn new() -> BasicAuthMethodDto {
    BasicAuthMethodDto {
      auth_type: None,
      uuid: None
    }
  }

  pub fn set_auth_type(&mut self, auth_type: String) {
    self.auth_type = Some(auth_type);
  }

  pub fn with_auth_type(mut self, auth_type: String) -> BasicAuthMethodDto {
    self.auth_type = Some(auth_type);
    self
  }

  pub fn auth_type(&self) -> Option<&String> {
    self.auth_type.as_ref()
  }

  pub fn reset_auth_type(&mut self) {
    self.auth_type = None;
  }

  pub fn set_uuid(&mut self, uuid: String) {
    self.uuid = Some(uuid);
  }

  pub fn with_uuid(mut self, uuid: String) -> BasicAuthMethodDto {
    self.uuid = Some(uuid);
    self
  }

  pub fn uuid(&self) -> Option<&String> {
    self.uuid.as_ref()
  }

  pub fn reset_uuid(&mut self) {
    self.uuid = None;
  }

}



