/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTokenDto {
    #[serde(rename = "readable", skip_serializing_if = "Option::is_none")]
    pub readable: Option<bool>,
    #[serde(rename = "writeable", skip_serializing_if = "Option::is_none")]
    pub writeable: Option<bool>,
}

impl CreateTokenDto {
    pub fn new() -> CreateTokenDto {
        CreateTokenDto {
            readable: None,
            writeable: None,
        }
    }
}


