/* 
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
#![allow(unused_imports)]

use serde_json::Value;
use bigdecimal::BigDecimal;
use chrono::{Date, NaiveDateTime, NaiveDate, DateTime, FixedOffset, Utc};

use crate::models::*;
use crate::date_serializer;
use crate::date_serializer_opt;
use crate::serialize_quoted_numbers;
use crate::serialize_quoted_numbers_opt;
//Uncomment this to deal with limited rfc support on server side
//use crate::datetime_serializer::*;

#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct LimitChangeEventDto {
  #[serde(rename = "eventTime")]
  #[serde(default)]
  //Uncomment this also to deal with limited rfc support on server side
  //#[serde(serialize_with = "serialize_dt", deserialize_with = "deserialize_dt")]
  event_time: Option<DateTime<Utc>>, 
  #[serde(rename = "newLimit")]
  #[serde(default)]
  new_limit: Option<i64>, 
  #[serde(rename = "oldLimit")]
  #[serde(default)]
  old_limit: Option<i64> 
}

impl LimitChangeEventDto {
  pub fn new() -> LimitChangeEventDto {
    LimitChangeEventDto {
      event_time: None,
      new_limit: None,
      old_limit: None
    }
  }

  pub fn set_event_time(&mut self, event_time: DateTime<Utc>) {
    self.event_time = Some(event_time);
  }

  pub fn with_event_time(mut self, event_time: DateTime<Utc>) -> LimitChangeEventDto {
    self.event_time = Some(event_time);
    self
  }

  pub fn event_time(&self) -> Option<&DateTime<Utc>> {
    self.event_time.as_ref()
  }

  pub fn reset_event_time(&mut self) {
    self.event_time = None;
  }

  pub fn set_new_limit(&mut self, new_limit: i64) {
    self.new_limit = Some(new_limit);
  }

  pub fn with_new_limit(mut self, new_limit: i64) -> LimitChangeEventDto {
    self.new_limit = Some(new_limit);
    self
  }

  pub fn new_limit(&self) -> Option<&i64> {
    self.new_limit.as_ref()
  }

  pub fn reset_new_limit(&mut self) {
    self.new_limit = None;
  }

  pub fn set_old_limit(&mut self, old_limit: i64) {
    self.old_limit = Some(old_limit);
  }

  pub fn with_old_limit(mut self, old_limit: i64) -> LimitChangeEventDto {
    self.old_limit = Some(old_limit);
    self
  }

  pub fn old_limit(&self) -> Option<&i64> {
    self.old_limit.as_ref()
  }

  pub fn reset_old_limit(&mut self) {
    self.old_limit = None;
  }


  pub fn validate(&self) {
  }

}


