/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SavedQuery {
    #[serde(rename = "alertRule", skip_serializing_if = "Option::is_none")]
    pub alert_rule: Option<crate::models::AlertRule>,
    #[serde(rename = "allowModification", skip_serializing_if = "Option::is_none")]
    pub allow_modification: Option<bool>,
    #[serde(rename = "applicationId", skip_serializing_if = "Option::is_none")]
    pub application_id: Option<String>,
    #[serde(rename = "applicationName", skip_serializing_if = "Option::is_none")]
    pub application_name: Option<String>,
    #[serde(rename = "applicationToken", skip_serializing_if = "Option::is_none")]
    pub application_token: Option<String>,
    #[serde(rename = "creatorEmail", skip_serializing_if = "Option::is_none")]
    pub creator_email: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "labelColor", skip_serializing_if = "Option::is_none")]
    pub label_color: Option<String>,
    #[serde(rename = "logseneAlertType", skip_serializing_if = "Option::is_none")]
    pub logsene_alert_type: Option<serde_json::Value>,
    #[serde(rename = "ownerEmail", skip_serializing_if = "Option::is_none")]
    pub owner_email: Option<String>,
    #[serde(rename = "queryName", skip_serializing_if = "Option::is_none")]
    pub query_name: Option<String>,
    #[serde(rename = "queryString", skip_serializing_if = "Option::is_none")]
    pub query_string: Option<String>,
    #[serde(rename = "userPermissions", skip_serializing_if = "Option::is_none")]
    pub user_permissions: Option<crate::models::UserPermissions>,
}

impl SavedQuery {
    pub fn new() -> SavedQuery {
        SavedQuery {
            alert_rule: None,
            allow_modification: None,
            application_id: None,
            application_name: None,
            application_token: None,
            creator_email: None,
            id: None,
            label_color: None,
            logsene_alert_type: None,
            owner_email: None,
            query_name: None,
            query_string: None,
            user_permissions: None,
        }
    }
}


