/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceIntegration {
    #[serde(rename = "appTypeId", skip_serializing_if = "Option::is_none")]
    pub app_type_id: Option<i64>,
    #[serde(rename = "appTypeName", skip_serializing_if = "Option::is_none")]
    pub app_type_name: Option<String>,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "externalProductId", skip_serializing_if = "Option::is_none")]
    pub external_product_id: Option<i64>,
    #[serde(rename = "externalProductName", skip_serializing_if = "Option::is_none")]
    pub external_product_name: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "integrationType", skip_serializing_if = "Option::is_none")]
    pub integration_type: Option<String>,
    #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
    pub ordinal: Option<i32>,
    #[serde(rename = "parentIntegrationId", skip_serializing_if = "Option::is_none")]
    pub parent_integration_id: Option<i64>,
    #[serde(rename = "sematextService", skip_serializing_if = "Option::is_none")]
    pub sematext_service: Option<String>,
    #[serde(rename = "visible", skip_serializing_if = "Option::is_none")]
    pub visible: Option<bool>,
}

impl ServiceIntegration {
    pub fn new() -> ServiceIntegration {
        ServiceIntegration {
            app_type_id: None,
            app_type_name: None,
            display_name: None,
            enabled: None,
            external_product_id: None,
            external_product_name: None,
            id: None,
            integration_type: None,
            ordinal: None,
            parent_integration_id: None,
            sematext_service: None,
            visible: None,
        }
    }
}


