/* 
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
#![allow(unused_imports)]

use serde_json::Value;
use bigdecimal::BigDecimal;
use chrono::{Date, NaiveDateTime, NaiveDate, DateTime, FixedOffset, Utc};

use crate::models::*;
use crate::date_serializer;
use crate::date_serializer_opt;
use crate::serialize_quoted_numbers;
use crate::serialize_quoted_numbers_opt;
//Uncomment this to deal with limited rfc support on server side
//use crate::datetime_serializer::*;

#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct SubscriptionsResponseEntry {
  #[serde(rename = "subscriptions")]
  #[serde(default)]
  subscriptions: Option<Vec<Subscription>> 
}

impl SubscriptionsResponseEntry {
  pub fn new() -> SubscriptionsResponseEntry {
    SubscriptionsResponseEntry {
      subscriptions: None
    }
  }

  pub fn set_subscriptions(&mut self, subscriptions: Vec<Subscription>) {
    self.subscriptions = Some(subscriptions);
  }

  pub fn with_subscriptions(mut self, subscriptions: Vec<Subscription>) -> SubscriptionsResponseEntry {
    self.subscriptions = Some(subscriptions);
    self
  }

  pub fn subscriptions(&self) -> Option<&Vec<Subscription>> {
    self.subscriptions.as_ref()
  }

  pub fn reset_subscriptions(&mut self) {
    self.subscriptions = None;
  }


  pub fn validate(&self) {
  }

}


