/* 
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
#![allow(unused_imports)]

use serde_json::Value;
use bigdecimal::BigDecimal;
use chrono::{Date, NaiveDateTime, NaiveDate, DateTime, FixedOffset, Utc};

use crate::models::*;
use crate::date_serializer;
use crate::date_serializer_opt;
use crate::serialize_quoted_numbers;
use crate::serialize_quoted_numbers_opt;
//Uncomment this to deal with limited rfc support on server side
//use crate::datetime_serializer::*;

#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct SubscriptionDashboardDto {
  #[serde(rename = "addresses")]
  #[serde(default)]
  addresses: Option<String>, 
  #[serde(rename = "dashboardId")]
  #[serde(default)]
  dashboard_id: Option<i64>, 
  #[serde(rename = "enable")]
  #[serde(default)]
  enable: Option<bool>, 
  #[serde(rename = "filters")]
  #[serde(default)]
  filters: Option<String>, 
  #[serde(rename = "frequency")]
  #[serde(default)]
  frequency: Option<String>, 
  #[serde(rename = "id")]
  #[serde(default)]
  id: Option<i64>, 
  #[serde(rename = "reportName")]
  #[serde(default)]
  report_name: Option<String>, 
  #[serde(rename = "sendTime")]
  #[serde(default)]
  //Uncomment this also to deal with limited rfc support on server side
  //#[serde(serialize_with = "serialize_dt", deserialize_with = "deserialize_dt")]
  send_time: Option<DateTime<Utc>>, 
  #[serde(rename = "subject")]
  #[serde(default)]
  subject: Option<String>, 
  #[serde(rename = "text")]
  #[serde(default)]
  text: Option<String>, 
  #[serde(rename = "timeRange")]
  #[serde(default)]
  time_range: Option<String> 
}

impl SubscriptionDashboardDto {
  pub fn new() -> SubscriptionDashboardDto {
    SubscriptionDashboardDto {
      addresses: None,
      dashboard_id: None,
      enable: None,
      filters: None,
      frequency: None,
      id: None,
      report_name: None,
      send_time: None,
      subject: None,
      text: None,
      time_range: None
    }
  }

  pub fn set_addresses(&mut self, addresses: String) {
    self.addresses = Some(addresses);
  }

  pub fn with_addresses(mut self, addresses: String) -> SubscriptionDashboardDto {
    self.addresses = Some(addresses);
    self
  }

  pub fn addresses(&self) -> Option<&String> {
    self.addresses.as_ref()
  }

  pub fn reset_addresses(&mut self) {
    self.addresses = None;
  }

  pub fn set_dashboard_id(&mut self, dashboard_id: i64) {
    self.dashboard_id = Some(dashboard_id);
  }

  pub fn with_dashboard_id(mut self, dashboard_id: i64) -> SubscriptionDashboardDto {
    self.dashboard_id = Some(dashboard_id);
    self
  }

  pub fn dashboard_id(&self) -> Option<&i64> {
    self.dashboard_id.as_ref()
  }

  pub fn reset_dashboard_id(&mut self) {
    self.dashboard_id = None;
  }

  pub fn set_enable(&mut self, enable: bool) {
    self.enable = Some(enable);
  }

  pub fn with_enable(mut self, enable: bool) -> SubscriptionDashboardDto {
    self.enable = Some(enable);
    self
  }

  pub fn enable(&self) -> Option<&bool> {
    self.enable.as_ref()
  }

  pub fn reset_enable(&mut self) {
    self.enable = None;
  }

  pub fn set_filters(&mut self, filters: String) {
    self.filters = Some(filters);
  }

  pub fn with_filters(mut self, filters: String) -> SubscriptionDashboardDto {
    self.filters = Some(filters);
    self
  }

  pub fn filters(&self) -> Option<&String> {
    self.filters.as_ref()
  }

  pub fn reset_filters(&mut self) {
    self.filters = None;
  }

  pub fn set_frequency(&mut self, frequency: String) {
    self.frequency = Some(frequency);
  }

  pub fn with_frequency(mut self, frequency: String) -> SubscriptionDashboardDto {
    self.frequency = Some(frequency);
    self
  }

  pub fn frequency(&self) -> Option<&String> {
    self.frequency.as_ref()
  }

  pub fn reset_frequency(&mut self) {
    self.frequency = None;
  }

  pub fn set_id(&mut self, id: i64) {
    self.id = Some(id);
  }

  pub fn with_id(mut self, id: i64) -> SubscriptionDashboardDto {
    self.id = Some(id);
    self
  }

  pub fn id(&self) -> Option<&i64> {
    self.id.as_ref()
  }

  pub fn reset_id(&mut self) {
    self.id = None;
  }

  pub fn set_report_name(&mut self, report_name: String) {
    self.report_name = Some(report_name);
  }

  pub fn with_report_name(mut self, report_name: String) -> SubscriptionDashboardDto {
    self.report_name = Some(report_name);
    self
  }

  pub fn report_name(&self) -> Option<&String> {
    self.report_name.as_ref()
  }

  pub fn reset_report_name(&mut self) {
    self.report_name = None;
  }

  pub fn set_send_time(&mut self, send_time: DateTime<Utc>) {
    self.send_time = Some(send_time);
  }

  pub fn with_send_time(mut self, send_time: DateTime<Utc>) -> SubscriptionDashboardDto {
    self.send_time = Some(send_time);
    self
  }

  pub fn send_time(&self) -> Option<&DateTime<Utc>> {
    self.send_time.as_ref()
  }

  pub fn reset_send_time(&mut self) {
    self.send_time = None;
  }

  pub fn set_subject(&mut self, subject: String) {
    self.subject = Some(subject);
  }

  pub fn with_subject(mut self, subject: String) -> SubscriptionDashboardDto {
    self.subject = Some(subject);
    self
  }

  pub fn subject(&self) -> Option<&String> {
    self.subject.as_ref()
  }

  pub fn reset_subject(&mut self) {
    self.subject = None;
  }

  pub fn set_text(&mut self, text: String) {
    self.text = Some(text);
  }

  pub fn with_text(mut self, text: String) -> SubscriptionDashboardDto {
    self.text = Some(text);
    self
  }

  pub fn text(&self) -> Option<&String> {
    self.text.as_ref()
  }

  pub fn reset_text(&mut self) {
    self.text = None;
  }

  pub fn set_time_range(&mut self, time_range: String) {
    self.time_range = Some(time_range);
  }

  pub fn with_time_range(mut self, time_range: String) -> SubscriptionDashboardDto {
    self.time_range = Some(time_range);
    self
  }

  pub fn time_range(&self) -> Option<&String> {
    self.time_range.as_ref()
  }

  pub fn reset_time_range(&mut self) {
    self.time_range = None;
  }


  pub fn validate(&self) {
  }

}


