/* 
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SubscriptionsResponseEntry {
  #[serde(rename = "subscriptions")]
  subscriptions: Option<Vec<::models::Subscription>>
}

impl SubscriptionsResponseEntry {
  pub fn new() -> SubscriptionsResponseEntry {
    SubscriptionsResponseEntry {
      subscriptions: None
    }
  }

  pub fn set_subscriptions(&mut self, subscriptions: Vec<::models::Subscription>) {
    self.subscriptions = Some(subscriptions);
  }

  pub fn with_subscriptions(mut self, subscriptions: Vec<::models::Subscription>) -> SubscriptionsResponseEntry {
    self.subscriptions = Some(subscriptions);
    self
  }

  pub fn subscriptions(&self) -> Option<&Vec<::models::Subscription>> {
    self.subscriptions.as_ref()
  }

  pub fn reset_subscriptions(&mut self) {
    self.subscriptions = None;
  }

}



