/* 
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TagNamesResponse {
  #[serde(rename = "names")]
  names: Vec<String>
}

impl TagNamesResponse {
  pub fn new(names: Vec<String>) -> TagNamesResponse {
    TagNamesResponse {
      names: names
    }
  }

  pub fn set_names(&mut self, names: Vec<String>) {
    self.names = names;
  }

  pub fn with_names(mut self, names: Vec<String>) -> TagNamesResponse {
    self.names = names;
    self
  }

  pub fn names(&self) -> &Vec<String> {
    &self.names
  }


}



