/* 
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TokensResponseEntry {
  #[serde(rename = "tokens")]
  tokens: Option<Vec<::models::TokenDto>>
}

impl TokensResponseEntry {
  pub fn new() -> TokensResponseEntry {
    TokensResponseEntry {
      tokens: None
    }
  }

  pub fn set_tokens(&mut self, tokens: Vec<::models::TokenDto>) {
    self.tokens = Some(tokens);
  }

  pub fn with_tokens(mut self, tokens: Vec<::models::TokenDto>) -> TokensResponseEntry {
    self.tokens = Some(tokens);
    self
  }

  pub fn tokens(&self) -> Option<&Vec<::models::TokenDto>> {
    self.tokens.as_ref()
  }

  pub fn reset_tokens(&mut self) {
    self.tokens = None;
  }

}



