/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAppInfo {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "ignorePercentage", skip_serializing_if = "Option::is_none")]
    pub ignore_percentage: Option<f64>,
    #[serde(rename = "maxEvents", skip_serializing_if = "Option::is_none")]
    pub max_events: Option<i64>,
    #[serde(rename = "maxLimitMB", skip_serializing_if = "Option::is_none")]
    pub max_limit_mb: Option<i64>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "sampling", skip_serializing_if = "Option::is_none")]
    pub sampling: Option<bool>,
    #[serde(rename = "samplingPercentage", skip_serializing_if = "Option::is_none")]
    pub sampling_percentage: Option<i32>,
    #[serde(rename = "staggering", skip_serializing_if = "Option::is_none")]
    pub staggering: Option<bool>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
}

impl UpdateAppInfo {
    pub fn new() -> UpdateAppInfo {
        UpdateAppInfo {
            description: None,
            ignore_percentage: None,
            max_events: None,
            max_limit_mb: None,
            name: None,
            sampling: None,
            sampling_percentage: None,
            staggering: None,
            status: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ACTIVE")]
    ACTIVE,
    #[serde(rename = "DISABLED")]
    DISABLED,
}

