/* 
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UsageResponseEntry {
  #[serde(rename = "usage")]
  usage: Option<::models::UsageDto>
}

impl UsageResponseEntry {
  pub fn new() -> UsageResponseEntry {
    UsageResponseEntry {
      usage: None
    }
  }

  pub fn set_usage(&mut self, usage: ::models::UsageDto) {
    self.usage = Some(usage);
  }

  pub fn with_usage(mut self, usage: ::models::UsageDto) -> UsageResponseEntry {
    self.usage = Some(usage);
    self
  }

  pub fn usage(&self) -> Option<&::models::UsageDto> {
    self.usage.as_ref()
  }

  pub fn reset_usage(&mut self) {
    self.usage = None;
  }

}



