/* 
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
#![allow(unused_imports)]

use serde_json::Value;
use bigdecimal::BigDecimal;
use chrono::{Date, NaiveDateTime, NaiveDate, DateTime, FixedOffset, Utc};

use crate::models::*;
use crate::date_serializer;
use crate::date_serializer_opt;
use crate::serialize_quoted_numbers;
use crate::serialize_quoted_numbers_opt;
//Uncomment this to deal with limited rfc support on server side
//use crate::datetime_serializer::*;

#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct UserInfo {
  #[serde(rename = "loginName")]
  #[serde(default)]
  login_name: Option<String> 
}

impl UserInfo {
  pub fn new() -> UserInfo {
    UserInfo {
      login_name: None
    }
  }

  pub fn set_login_name(&mut self, login_name: String) {
    self.login_name = Some(login_name);
  }

  pub fn with_login_name(mut self, login_name: String) -> UserInfo {
    self.login_name = Some(login_name);
    self
  }

  pub fn login_name(&self) -> Option<&String> {
    self.login_name.as_ref()
  }

  pub fn reset_login_name(&mut self) {
    self.login_name = None;
  }


  pub fn validate(&self) {
  }

}


