name: Rust

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name : Set up Rust
        uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v2
        - name: Publish
      - uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_TOKEN }}
      - run: cargo build
      - run: cargo publish
      - run: cargo owner --add sematext-packages
      
    
