name: Rust

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1                
      - name: Checkout
        uses: actions/checkout@v2        
      - name : Login
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_TOKEN }}      
      - name : Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name : Publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
      - name : Assign ownership
        uses: actions-rs/cargo@v1
        with:
          command: owner
          args : --add sematext-packages

      
    
